// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKdRt3o92KnFvbHy7mhBwfuktI32SxQPk',
    appId: '1:842766703228:web:3498230a470734d198c7f9',
    messagingSenderId: '842766703228',
    projectId: 'gymnotes-1e313',
    authDomain: 'gymnotes-1e313.firebaseapp.com',
    storageBucket: 'gymnotes-1e313.appspot.com',
    measurementId: 'G-EH3H0CNTWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdXNuSNs91I05WH1YVp6Ke_Km_MweU91Y',
    appId: '1:842766703228:android:5430d43121f8a2b898c7f9',
    messagingSenderId: '842766703228',
    projectId: 'gymnotes-1e313',
    storageBucket: 'gymnotes-1e313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXiHGiAfYfiGj36e00Gilk31hCD4aXh1U',
    appId: '1:842766703228:ios:069bb05257ad4f3d98c7f9',
    messagingSenderId: '842766703228',
    projectId: 'gymnotes-1e313',
    storageBucket: 'gymnotes-1e313.appspot.com',
    iosClientId: '842766703228-ret2v7m4gfbqkvdrinpt6pqhghokphbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXiHGiAfYfiGj36e00Gilk31hCD4aXh1U',
    appId: '1:842766703228:ios:069bb05257ad4f3d98c7f9',
    messagingSenderId: '842766703228',
    projectId: 'gymnotes-1e313',
    storageBucket: 'gymnotes-1e313.appspot.com',
    iosClientId: '842766703228-ret2v7m4gfbqkvdrinpt6pqhghokphbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymnotes',
  );
}
